version: '3'

services:
  pauta-api:
    container_name: desafio-pauta-api
    image: desafio-pauta:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    links:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - messages
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - messages
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
  messages:
    name: messages

